### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by MyLhassane** [learn-web-scraping/node_js_pagination#1]
Create new issueText that is not a quote

> Text that is a quote

**Comment by aryan1703** [comment]
I would like to contribute to this project. Can you explain your requirements for this project? What do you mean by "Create new issueText that is not a quote"?

**Comment by MyLhassane** [comment]
> I would like to contribute to this project. Can you explain your requirements for this project? What do you mean by "Create new issueText that is not a quote"?

I apologize for the misunderstanding that came from me

This issue is just a test

But I'm glad to This This initiative  that came from you

my regards 
Hassan

**Comment by MyLhassane** [comment]
Issue resolved

**Comment by aryan1703** [comment]
No worries, sir. If you need any help with your project, I am ready to contribute.
